spring:
  application:
    name: all-in-one

  datasource:
    url: jdbc:postgresql://db:5432/e-commerce
    username: admin
    password: admin

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  kafka:
    bootstrap-servers: kakfa3:8099,kafka2:8098,kafka1:8097
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      outbound-topic: order-purchased-topic

server:
  port: 7072