spring:
  application:
    name: producer_app

  datasource:
    url: jdbc:postgresql://localhost:54320/e-commerce
    username: admin
    password: admin

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true


  kafka:
    bootstrap-servers: localhost:8097,localhost:8099,localhost:8098
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      outbound-topic: order-purchased-topic
      properties:
          spring.json.type.mapping: OrderDTO:com.example.producer_app.dtos.OrderDTO
server:
  port: 7070
